verbose=false
maxDepth=5

world=BlockWorld
initialState=[on(a,c),ontable(b),ontable(c),clear(a),clear(b),handempty]
goal=[on(c, b), on(b, a), clear(c)]

#world=Registers
#initialState=[register(eax, 0)]
#goal=[register(eax, 0 - 1 - 1)]

#world=Stack
#initialState=[on(2, on(1, bottom))]
#goal=[on(-1, _)]

#world=StackASMGen
#initialState=[top(bottom)]
#goal=[top(c1 + (c2 - c3))]
